### ISSUE TITLE
Let users search members by their uid or nick

### ISSUE THREAD

**Issue by JDrit** [cgonyeo/brandrethstats#15]
this way stuff like slackwill and dgonyeo are actual results since no one actually spell slackwill's last name.

**Comment by cgonyeo** [comment]
The visitors page now includes nicknames, to facilitate Ctrl-Fing to someone. Is this what you meant?

**Comment by cgonyeo** [comment]
Wasn't sure what you wanted with this. There's no way to search through "members" other than scrolling through the visitors page, as the search does a textual search through the entries. Spelling someone's name isn't a big concern, because you don't type anything in, you scroll down the page and find the name.

**Comment by JDrit** [comment]
What you did was want I meant. I now can do ctrl-F for "mike5" without having to know mike5's real name. I was also thinking about members' UID's, so if I did ctrl-F for "dgonyeo" I would get you.

**Comment by cgonyeo** [comment]
I don't think usernames is required, I might run out of space for some people and you don't casually refer to me as dgonyeo.

**Comment by JDrit** [comment]
This is just the cherry on top but you could implement some search field that searches by uid, nick, and full name, similar to what csh member profiles has. Yes no one calls you by your uid but what about mike5, swanboy, clockfort, etc. Besides that, it is a cool project!!

**Comment by cgonyeo** [comment]
ctrl-f for mike5, swan, or clockfort and you get the corresponding people (ignore thomas, that's been fixed)

**Comment by JDrit** [comment]
Yea, like I said what you implemented was what I had mentioned at the beginning of this thread.
