### ISSUE TITLE
Provide links from textual entries to images of pages

### ISSUE THREAD

**Issue by bkuker** [cgonyeo/brandrethstats#17]
I'd love to be able to see the digital picture of the actual page(s) linked from the text of each guestbook entry.

**Comment by cgonyeo** [comment]
We're planning on including images of drawings people have made in the guest book, would this be sufficient? Most of the pictures of the textual entries were taken at 2 am on an iPod by lantern/flashlight and I might want to retake some of them before integrating them in the site. The drawings we were more careful about getting better pictures of.

**Comment by bkuker** [comment]
Understood!
