### ISSUE TITLE
Guestbook entries are not HTML-escaped on display

### ISSUE THREAD

**Issue by digitalcora** [cgonyeo/brandrethstats#20]
This led to entries getting cut off in the case of my "&lt;/3 nature" comments. Better fix it before someone hand-writes an XSS attack in the guestbook on their next trip. =p

**Comment by cgonyeo** [comment]
I'm aware of this, and cohoe has already written out an alert telling me to fix it, so I'll need to get this done before I update the guestbook next.

**Comment by cgonyeo** [comment]
I only escaped <, >, and &. My limited knowledge of html says this might be good enough.

**Comment by digitalcora** [comment]
You should also escape `"` to `&quot;` and `'` to `&#039;`, otherwise you're vulnerable to attribute value injection. (Well, technically you might not be vulnerable given the limited functionality the site currently has, but I wouldn't bet my database on it.)
